backend/controllers/SiteController.php
<?php

/**
 * itech-mobile.ru
 * @author anton
 */

namespace backend\controllers;

use common\models\Church;
use common\models\Need;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

use backend\models\LoginForm;

/**
 * Default controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login'],
                        'allow'   => true,
                    ],
                    [
                        'actions' => ['error'],
                        'allow'   => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                    [
                        'actions' => ['index', 'oferta', 'sendmail', 'pay', 'success', 'error'],
                        'allow'   => true,

                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $this->layout='site.twig';
        Yii::$app->view->params['hideFooter'] = true;
        return $this->render('index',['message' => false]);
    }

    public function actionOferta()
    {
        return $this->render('oferta');
    }

    public function actionSendmail()
    {
        $fio = Yii::$app->request->post('fio');
        $email = Yii::$app->request->post('email');
        $theme = Yii::$app->request->post('theme');
        $phone = Yii::$app->request->post('phone');
        $message = Yii::$app->request->post('message');
        $to ='vinveg@mail.ru';
        $subject = "$fio отправил сообщение с сайта vsemmirom.com.";
        $message_full = "<b>ФИО:</b> $fio<br /><b>email:</b> $email<br /><b>Тема обращения:</b> $theme <br /><b>Телефон:</b> $phone<br /><b>Сообщение:</b><br /><br />$message";
        $headers  = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

        $headers .= 'To:'.$to."\r\n";
        $headers .= 'From: vsemmirom@site.com'."\r\n";
        mail($to,$subject,$message_full,$headers);
        return $this->redirect('/?message_send=ok');
    }

    public function beforeAction($action)
    {
        // ...set `$this->enableCsrfValidation` here based on some conditions...
        // call parent method that will check CSRF if such property is true.
        if ($action->id === 'login') {
            # code...
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if (Yii::$app->request->getMethod() == 'POST' && $model->load(Yii::$app->request->post()) && $model->login()) {
//            return $this->goBack();
            return Yii::$app->getResponse()->redirect(Yii::$app->getUrlManager()->createUrl('/search'));
        } else {
            Yii::$app->view->params['hideFooter'] = true;
            return $this->render('login.twig', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return Yii::$app->getResponse()->redirect(Yii::$app->getUrlManager()->createUrl('../site'));
//        return $this->goHome();
    }

    public function actionPay()
    {
        return $this->render('pay.php', []);
    }

    public function actionSuccess()
    {
        $headers  = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
        $headers .= 'From: vsemirom@site.com' . "\r\n";
        $fio = Yii::$app->request->get('fio');
        if ( (Yii::$app->request->get('need_id') && Yii::$app->request->get('need_id') != 'all') && Yii::$app->request->get('amount'))
        {

            $need_id = Yii::$app->request->get('need_id');
            $need = Need::findOne($need_id);
            $church = Church::findOne($need->churchid);
            $need->collected = $need->collected + Yii::$app->request->get("amount");
            $need->save();


            $need_name = $need->name;
            $church_name = $church->name;
            mail('hr2amo015@yandex.ru','Был совершен платеж.',"Пользователь $fio пожертвовал на: $need_name, для: $church_name, сумму: ".Yii::$app->request->get("amount"),$headers);


            if (Yii::$app->request->get('email'))
            {
                $to = Yii::$app->request->get('email');
                $subject = "Платеж прошел успешно.";
                $message_full = "Ваш платеж принят. Благодарим вас за пожертвование.";

                mail($to,$subject,$message_full,$headers);
            }
        }
        elseif (Yii::$app->request->get('church_id') && Yii::$app->request->get('amount'))
        {
            $church = Church::findOne(Yii::$app->request->get('church_id'));
            $church_name =$church->name;
            mail('hr2amo015@yandex.ru','Был совершен платеж.',"Пользователь $fio пожертвовал на все нужны для: $church_name, сумму: ".Yii::$app->request->get("amount"),$headers);

            if (Yii::$app->request->get('email'))
            {
                $to = Yii::$app->request->get('email');
                $subject = "Платеж прошел успешно.";
                $message_full = "Ваш платеж принят. Благодарим вас за пожертвование.";

                mail($to,$subject,$message_full,$headers);
            }
        }
        return $this->render("success.php", []);
    }

    public function actionError()
    {
        return $this->render("fail.php");
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/fail.php
<style>
    .fail {
        padding-top: 10%;
        margin-bottom: 29%;
    }
</style>
<html>
<head>
    <title>Платеж не прошел.</title>
</head>
<div class="fail">
    <h1>Платеж не прошел.</h1>
    <p>По какой то причине платеж не прошел.</p>
</div>
</html>

backend/views/site/index.php
<?php
/* @var $this yii\web\View */

$this->title = 'Всем миром';

if (Yii::$app->request->get('message_send') == 'ok')
{
    echo "<script>
        alert('Сообщение отправлено.');
    </script>";
}?>

<div class="index">
    <div class='head'>
        <div class="menu">
            <ul>
                <li><a href="#">Блог</a></li>
                <li><a href="#">Контакты</a></li>
            </ul>
        </div>
        <div class="text-block">
            <p class="title">Всем миром</p>
            <p class="small-text">Мобильное приложение для сбора пожертвований<br /> на реконструкцияю храмов и монастырей <br />Русской Православной Церкви</p>
            <a href="http://www.apple.com/" target="_blank" class="button">Скачать приложение в APP STORE</a>
        </div>
    </div>
<!--    <div class="sub-head">-->
<!--        <p class="title">-->
<!--            Свести вместе тех, кто хочет и может помочь делу <br />восстановления церквей и сами храмы.-->
<!--        </p>-->
<!--        <p class="small-text">Проект для не равнодушных людей,  желающих принять участие в благом делевосстановления и строительства</p>-->
<!--    </div>-->
    <div class="patriarh">
        <div class="photo">
            <img src="images/review_photo.png" alt="">
        </div>
        <div class="content">
            <p class="title">Патриарх Московский и всея Руси Кирилл</p>
            <p  class="quote"><img src="images/quote.png" alt=""></p>

            <p class="comment">Строительство храма - это всегда некий подвиг, и духовный, и материальный.<br />В строительстве Храма обнаруживается подлинное стремление людей<br />
                к общению с Богом. Вот почему в молитве на освящение храма и говорится,<br />что тем, кто построил храм, прощаются грехи. Подвиг возведения храма<br />
                действительно принимается Господом как жертва благоуханная, угодная,<br />потому что через созидание Божиего храма души человеческие обращаются<br />
                ко спасению.</p>
<!--            <p class="small-text">Проект “Всем миром” создан по благословению Управления делами Московской Патриархии, <br /> для неравнодушных людей, желающих принять участие-->
<!--            в благом деле восстановления <br /> и строительства Храмов.</p>-->
        </div>
    </div>
    <div class="review">


            <p class="title">
                Проект "Всем миром" объединяет тех, кто заинтересован <br /> в возраждении архитектурного наследия<br />  и духовной культуры нашей страны.
            </p>
            <p class="comment">
                По благословению митрополита Санкт-Петербургского и Ладожского Варсонофия,<br />управляющего делами Московской Патриархии РПЦ.
            </p>



    </div>
    <div class="services">
        <p class="title">
            Удобный сервис для поиска информации о храмах, <br /> монастырях, часовнях и их нуждах, искать можно по:
        </p>
        <ul class="icons">
            <li>
                <img src="images/map.png" alt="">
                <span>Карте</span>
            </li>
            <li>
                <img src="images/flag.png" alt="">
                <span>Региону</span>
            </li>
            <li  class="last">
                <img src="images/city.png" alt="">
                <span>Городу</span>
            </li>
        </ul>
        <p class="small-text">Каждый посетитель может посмотреть подробную информацию о заинтересовавшем его храме или монастыре.</p>
    </div>
    <div class="sections">
        <div class="black" id="black">
            <div class="container-dialog">
                <div class="close-dialog"><img src="images/close.png" alt=""></div>
                <div class="dialog">
                    <p class="small-text">Вы можете оказать помощь Храмам<br />
                        установив приложение на свой iPhone или iPad.</p>
                    <a href="http://www.apple.com/" target="_blank" class="button-dialog">Перейти в App Store и установить приложение</a>
                    <br />
                    <a href="/site/oferta" target="_blank" class="oferta">Договор оферты</a>
                    <p class="small-text">Приложение для устройств на базе Android<br />
                        в данный момент не доступно, находится в разработке.</p>
                    <br />
                    <div class="fotter-dialog">
                        <p class="small-text">Либо Вы можете оказать пожертвование связавшись<br />
                            с нами. В качестве темы укажите “Хочу сделать пожертвование”.</p>
                        <a href="#contacts" class="button-dialog contact-us">Напишите нам и сделайте пожертвование</a>
                    </div>
                </div>
            </div>
        </div>
        <p class="title">
            <img src="images/flash.png" alt="">
            Созданы разделы для срочной помощи храмам
        </p>
        <a class="button want-to-help" href="#black">Хочу оказать помощь</a>
        <div class="img">
            <div>
                <p class="title">Мы позаботились о целевом использовании средств</p>
                <p class="small-text">После сбора нужной суммы и по завершении работ (или на промежуточных этапах) все жертвователи смогут<br /> посмотреть фотоотчет о том,
                как были истрачены их деньги.</p>
            </div>
            <div class="spacer"></div>
            <div>
                <p class="title">Следите за дальнейшей судьбой храма</p>
                <p class="small-text">Получайте сведения о последующем использовании пожертвованных средств. Отчет об использовании пожертвований<br />
                можно найти в открытом доступе, <u>в нашем блоге</u> или получить на свой электронный адрес</p>
            </div>
        </div>
    </div>
    <div class="losung">
        <p class="title">Жертвуй от чистого сердца</p>
        <p class="small-text">Благотворители смогут пожертвовать, как небольшие суммы, так и серьезные средства.<br />
        Персональная информация жертвователей будет надежно защищена. Все сведения из нашей базы данных <br />
        подвергаются тщательной проверке.</p>
        <a class="button want-to-help" href="#black">Хочу отказать помощь</a>
        <div class="img">
            <p class="title">На каждой литургии в церкви звучит возглас:</p>
            <p class="liturgiya">"О создателях святого храма сего Господу помолимся!" <br /><span>На этот призыв мы отвечаем самой главной христьянской молитвой</span></p>
        </div>
    </div>
    <div class="contacts">
        <div class="form">
            <p class="title" id="contacts">Контакты</p>
            <form action="<?php echo Yii::$app->getUrlManager()->createUrl('site/sendmail') ?>" method="post">
               <input type="hidden" name="_csrf" value="<?php echo Yii::$app->request->getCsrfToken() ?>"/>
               <fieldset>
                <input type="text" class="form-input" placeholder="Ваше имя: *" name="fio">
                <input type="text" class="form-input" placeholder="Email: *" name="email">
               </fieldset>
               <fieldset>
                <select name="theme" id="" class="form-input">
                    <option value="">Выберите тему обращения</option>
                    <option value="Сделать пожертвование">Сделать пожертвование</option>
                    <option value="Сотрудничество">Сотрудничество</option>
                    <option value="Другое">Другое</option>
                </select>
                <input type="text" class="form-input" placeholder="Телефон: *" name="phone">
               </fieldset>
               <fieldset>
                   <textarea name="message" cols="121" rows="6" placeholder="Введите текст сообщения: *"></textarea>
               </fieldset>
                <input class="btn-submit" type="submit" value="Отправить">
            </form>
        </div>
    </div>
    <div class="footer">
        <div class="column1">
            <p class="title">Телефон, Email:</p>
            <p class="phone">+7 (874) 234 57 62</p>
            <p class="email"><a class="email" href="mail-to:info@vsemmirom.com">info@vsemmirom.com</a></p>
        </div>
        <div class="column2">
            <p class="title">Адрес:</p>
            <p class="adress">465923 Россия, г. Москва  </p>
            <p class="adress-2">Новорижское шоссе, д. 34, каб. 289</p>
        </div>

        <div class="column3">
            <p class="first"><a href="/site/oferta">Договор оферты</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Наш блог</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://vk.com">Группа Вконтакте</a></p>
        </div>
        <div class="column4"><img src="images/app_store.png" alt=""></div>
        <div class="clearfix"></div>
        <div class="bottom-line">

            <div class="tm">Copyright © 2016 Автономная некоммерческая организация «Информационный центр по восстановлению храмов и монастырей «Храмо-созидатель»</div>
        </div>
    </div>

<!--    <div class="site-index text-center">-->
<!--            <p><a class="btn btn-info text-uppercase" href="/admin/search">Страница поиска</a></p>-->
<!---->
<!---->
<!--    </div>-->
</div>

backend/views/site/oferta.php
<div class="aferta">

    <h1>Оферта</h1>



</div>

backend/views/site/pay.php
<style>
    .pay
    {
        margin: 0 auto;
        width: 60%;
        padding-top: 20%;
    }
    .pay form fieldset label
    {
        width: 40%;
    }
    .pay form fieldset input[type='text'], input[type='email'] {
        height: 33px;
        width: 40%;
    }
    .pay form fieldset
    {
        margin-bottom: 10px;
    }
    .pay form fieldset input[type='submit']
    {
        padding: 8px 40px 8px 40px;
        font-weight: bold;
    }
</style>
<html>
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Форма оплаты</title>
</head>
<body>
<div class="pay">
    <form action="https://demomoney.yandex.ru/eshop.xml" method="post">
        <!-- Обязательные поля -->
        <input name="paymentType" value="" type="hidden">
        <input name="shopId" value="151" type="hidden"/>
        <input name="scid" value="363" type="hidden"/>
        <input type="hidden" value="http://vsemmirom.loc/site/pay/" name="shopSuccessURL">
        <input type="hidden" value="http://vsemmirom.loc/site/pay/" name="shopFailURL">
        <fieldset>
            <label for="sum">Сумма пожертвования:</label>
            <input name="sum" id="sum" value="100" type="text"/>
        </fieldset>
        <fieldset>
            <label for="user">Номер пользователя:</label>
            <input name="customerNumber" id="user" value="100500" type="text"/>
        </fieldset>
        <fieldset>
            <label for="phone">Телефон:</label>
            <input name="cps_phone" id="phone" value="79110000000" type="text"/>
        </fieldset>
        <fieldset>
            <label for="email">Email:</label>
            <input name="cps_email" id="email" value="user@domain.com" type="email"/>
        </fieldset>
        <fieldset align="right" style="padding-right: 19%">
            <input type="submit" value="Оплатить">
        </fieldset>

    </form>
</div>
</body>
</html>

backend/views/site/success.php
<style>
    .success {
        padding-top: 10%;
        margin-bottom: 29%;
    }
</style>
<html>
<head>
    <title>Платеж прошел успешно.</title>
</head>
<div class="success">
    <h1>Благодарим Вас за пожертвование.</h1>
    <p>Ваш платеж принят.</p>
</div>
</html>